name: supabase-backup

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

env:
  BACKUP_ENABLED: true

jobs:
  backup_and_reset:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_BD_URL }}
      SUPABASE_DB_URL_DEV: ${{ secrets.SUPABASE_BD_URL_DEV }}
      BACKUP_ENABLED: ${{ vars.BACKUP_ENABLED }}

    steps:

      # --- VALIDACIÃ“N ---
      - name: Check if backups are enabled
        run: |
          if [ "$BACKUP_ENABLED" != "true" ]; then
            echo "ðŸ”• Backups are disabled. Exiting workflow."
            exit 0
          fi

      # --- SETUP ---
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Prepare backup folder
        run: mkdir -p prisma/backups/prod

      # --- BACKUP ---
      - name: Backup Roles
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/prod/roles.sql --role-only

      - name: Backup Schema
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/prod/schema.sql

      - name: Backup Data
        run: supabase db dump --db-url "$SUPABASE_DB_URL" -f prisma/backups/prod/data.sql --data-only --use-copy

      # --- COMMIT ---
      - name: Commit backups to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Supabase backup"

      # --- RESET DEV ---
      - name: Debug DEV URL
        run: echo "Resetting DEV database at:" '$SUPABASE_DB_URL_DEV'"

      - name: Reset DEV database
        run: supabase -y db reset --db-url "$SUPABASE_DB_URL_DEV"

      # --- RESTORE DEV ---
      - name: Restore DEV roles
        run: psql "$SUPABASE_DB_URL_DEV" -f prisma/backups/prod/roles.sql

      - name: Restore DEV schema
        run: psql "$SUPABASE_DB_URL_DEV" -f prisma/backups/prod/schema.sql

      - name: Restore DEV data
        run: psql "$SUPABASE_DB_URL_DEV" -f prisma/backups/prod/data.sql
